### PR TITLE
Sfml2 port

### PR DESCRIPTION
**Pull request by matthewharvey**
Assorted fixes and some very minor cleanups.

Specifically fixes rendering of certain items, because of some difference between pixel space and "game space" in the rendering code.

Currently trying to figure out why the tool boxes (other than the item one) aren't rendering correctly, but am totally baffled.

### CODE REVIEW

**Comment by fabianschuiki** [comment]
Hey @matthewharvey, thank you very much for your work. I'm glad to see the project is still alive even though I'm currently having trouble to find time to work on it.

**Comment by matthewharvey** [comment]
Hi Fabian, thank-you very much for your work on this project!

I'm going to keep picking away at it over the next little while, but I'm not making fast progress by any means.

**Comment by HoyteKashif** [comment]
What are some areas that still need work?

**Comment by matthewharvey** [comment]
I haven't really isolated any yet. There are certainly places where it hasn't been completed at all (condos come to mind, along with the star system), but I was just going to play around with it for a bit and maybe clean up the code a little in preparation for some of those larger features. I have a couple more commits in my branch now.

Is there anything big that hasn't been fixed since the change to SFML2? I haven't noticed any, but that doesn't mean there aren't any.

**Pull request merged**
